"""empty message

Revision ID: 247c99c767a2
Revises: 5a37d63b5e1a
Create Date: 2023-01-07 18:32:57.035540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '247c99c767a2'
down_revision = '5a37d63b5e1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('levels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subjects_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('levels_subject_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'subjects', ['subjects_id'], ['id'])
        batch_op.drop_column('subject_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('levels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('levels_subject_id_fkey', 'subjects', ['subject_id'], ['id'])
        batch_op.drop_column('subjects_id')

    # ### end Alembic commands ###
