"""empty message

Revision ID: 5a37d63b5e1a
Revises: 6f6143675320
Create Date: 2023-01-07 18:17:06.386671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a37d63b5e1a'
down_revision = '6f6143675320'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('level')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('level',
    sa.Column('levels_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('subjects_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['levels_id'], ['levels.id'], name='level_levels_id_fkey'),
    sa.ForeignKeyConstraint(['subjects_id'], ['subjects.id'], name='level_subjects_id_fkey')
    )
    # ### end Alembic commands ###
