"""empty message

Revision ID: 6f6143675320
Revises: cdb95c0c417a
Create Date: 2023-01-07 18:12:36.566880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f6143675320'
down_revision = 'cdb95c0c417a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('level',
    sa.Column('levels_id', sa.Integer(), nullable=True),
    sa.Column('subjects_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['levels_id'], ['levels.id'], ),
    sa.ForeignKeyConstraint(['subjects_id'], ['subjects.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('level')
    # ### end Alembic commands ###
